- name: Provision AWS server locally
  hosts: local
  tasks:
   - name: Update package list
     ansible.builtin.apt:
      update_cache: yes

   - name: install packages
     ansible.builtin.apt:
      name:
        - nginx
        - postgresql