- name: Provision AWS server locally
  hosts: local
  become: true
  vars_files:
    - ansible/variables.yaml
  tasks:
    - name: Update package list
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: install packages
      ansible.builtin.apt:
        name:
          - python3-pip
          - python3-venv
          - nginx
          - postgresql
          - certbot python3-certbot-nginx
        state: present

    - name: install certificates from certbot
      ansible.builtin.shell: "sudo certbot --nginx -d {{ domain }} -d www.{{ domain }}"