- name: Provision AWS server locally
  hosts: local
  become: true
  vars_files:
    - variables.yaml
  tasks:
    - name: initial host setup
      tags: setup
      block:
        - name: Update package list
          ansible.builtin.apt:
            update_cache: yes
            cache_valid_time: 3600

        - name: install packages
          ansible.builtin.apt:
            name:
              - python3-pip
              - python3-venv
              - nginx
              - postgresql
              - certbot
              - python3-certbot-nginx
              - python3-psycopg
              - acl
            state: present

    - name: configure ufw
      tags: ufw
      block:
        - name: allow openssh and nginx full
          ansible.builtin.shell: 'for app in "OpenSSH" "Nginx Full"; do sudo ufw allow "$app"; done'

        - name: enable ufw
          ansible.builtin.command: "sudo ufw --force enable"

    - name: configure nginx
      tags: nginx
      block:
        - name: copy nginx server block to sites-available
          ansible.builtin.template:
            src: nginx-server-block.jinja
            dest: /etc/nginx/sites-available/{{ domain }}

        - name: create symlink between sites-available and sites-enabled for server block
          ansible.builtin.file:
            src: /etc/nginx/sites-available/{{ domain }}
            dest: /etc/nginx/sites-enabled/{{ domain }}
            state: link

        - name: install certificates from certbot
          tags: certbot
          ansible.builtin.command:
            cmd: "sudo certbot --nginx -d {{ domain }} -d www.{{ domain }} -m {{ email }} --agree-tos -n"
            creates: "/etc/letsencrypt/live/{{ domain }}"

        - name: test nginx configuration
          ansible.builtin.command: "sudo nginx -t"

        - name: reload nginx
          ansible.builtin.systemd_service:
            name: nginx
            state: reloaded

    - name: configure postgres
      tags: postgres
      become_user: postgres
      block:
        - name: create the database user
          community.postgresql.postgresql_user:
            name: "{{ db_user }}"
            password: "{{ db_user_password }}"
            configuration:
              client_encoding: utf8
              default_transaction_isolation: read committed
              timezone: "{{ timezone }}"

        - name: create the database
          community.postgresql.postgresql_db:
            name: "{{ db_name }}"
            owner: "{{ db_user }}"

    - name: setup django
      tags: django
      become: false
      block:
        - name: create project directory
          ansible.builtin.file:
            path: ~/{{ django_project }}/
            state: directory
          register: django_project_dir

        - name: create virtual environment in directory and install modules
          ansible.builtin.pip:
            chdir: "{{ django_project_dir.path }}"
            virtualenv: env
            virtualenv_command: python3 -m venv
            name:
              - django-ninja
              - uvicorn
              - uvicorn-worker
              - gunicorn
              - psycopg[binary]
          register: virtual_env

        - name: create a django project
          ansible.builtin.command:
            chdir: "{{ django_project_dir.path }}"
            cmd: "{{ virtual_env.virtualenv }}/bin/django-admin startproject {{ django_project }} {{ django_project_dir.path }}"
            creates: "{{ django_project_dir.path }}/manage.py"

        - name: configure settings.py
          ansible.builtin.template:
            src: settings.py.jinja
            dest: "{{django_project_dir.path}}{{django_project}}/settings.py"

        - name: makemigrations
          community.general.django_manage:
            command: makemigrations
            project_path: "{{ django_project_dir.path }}"
            virtualenv: "{{ virtual_env.virtualenv }}"

        - name: migrate
          community.general.django_manage:
            command: migrate
            project_path: "{{ django_project_dir.path }}"
            virtualenv: "{{ virtual_env.virtualenv }}"

        # - name: start test server
        #   community.general.django_manage:
        #     command: runserver
        #     project_path: "{{ django_project_dir.path }}"
        #     virtualenv: "{{ virtual_env.virtualenv }}"